---
title: "Lenin on terror as state policy"
author: Austin Hoover
date: 2026-06-02
categories:
  - books
  - history
  - Russia
---

From *The Gulag Archipelago (Volume 1)*:

> [Lenin] "Comrade Kursky! In my opinion we ought to extend the use of execution by shooting (allowing the substitution of exile abroad) to all activities of the Mensheviks, SR's, etc. We ought to find a formulation that would connect these activities *with the international bourgeoisie*."
>
> [Solzhenitsyn] *To extend the use of execution by shooting!* Nothing left to the imagination there! (And did they exile very many?) *Terror is a method of persuasion.* This, too, could hardly be misunderstood.
>
> But Kursky, nonetheless, still didn't get the whole idea. In all probability, what he couldn't quite work out was a way of formulating that formulation, a way of working in that very matter of *connection*. The next day, he called on the Chairman of the Council of People's Commissars, Lenin, for clarification. We have no way of knowing what took place during their conversation. But following it up, on May 17, Lenin sent a second letter from Gorki:
>
> [Lenin] Comrade Kursky!
>
> As a sequel to our conversation, I am sending you an outline of a supplementary paragraph for the Criminal Code... The basic concept, I hope, is clear, notwithstanding all the shortcomings of the rough draft: openly to set forth a statute which is both principled and politically truthful (and not just juridically narrow) to supply the motivation for the *essence* and the *justification* of terror, its necessity, its limits.
>
> The court must not exclude terror. It would be self-deception or deceit to promise this, and in order to provide it with a foundation and to legalize it in a principled way, clearly and without hypocrisy and without embellishment, it is necessary to formulate it as broadly as possible, for only revolutionary righteousness and a revolutionary conscience will provide the conditions for applying it more or less broadly in practice.
>
> With Communist greetings,
>
> Lenin
