---
title: Links
---


* Blogs \
    * [Alexander Pruss](http://alexanderpruss.blogspot.com)
    * [Asymptotia](https://asymptotia.com/category/science/string-theory/)
    * [Backreaction](http://backreaction.blogspot.com)
    * [Bactra](http://bactra.org/notebooks/)
    * [China Talk](https://www.chinatalk.media)
    * [Condensed Concepts](https://condensedconcepts.blogspot.com)
    * [Edward Feser](https://edwardfeser.blogspot.com)
    * [ex-apologist](http://exapologist.blogspot.com)
    * [Fake Nous](https://fakenous.substack.com)
    * [lillog](https://lilianweng.github.io)
    * [Nanoscale Views](http://nanoscale.blogspot.com)
    * [Not Even Wrong](https://www.math.columbia.edu/~woit/wordpress/)
    * [Notes from a data witch](https://blog.djnavarro.net)
    * [Of particular significance](https://profmattstrassler.com/blog/)
    * [Physics Matt](http://www.physicsmatt.com/blog/)
    * [Preposteroous Universe](https://www.preposterousuniverse.com/blog/)
    * [Scott Hawley](https://drscotthawley.github.io/blog/)
    * [Shtetl-Optimized](https://scottaaronson.blog)
    * [The Splintered Mind](http://schwitzsplinters.blogspot.com)
    * [Statistical Modeling](https://statmodeling.stat.columbia.edu)
    * [Danny Yee's Book Reviews](https://dannyreviews.com)
* People
    * [Alexander Pruss](http://alexanderpruss.com)
    * [Adrian Oeftiger](http://www.oeftiger.net)
    * [Brian Cutter](https://sites.google.com/site/cutterbc/home)
    * [Charles Sebens](https://sites.google.com/site/csebens/home)
    * [Christopher Gregory Weaver](https://christophergregoryweaver.com/about-4)
    * [David Kipping](http://davidkipping.co.uk)
    * [Eddie Chen](https://www.eddykemingchen.net)
    * [Graham Oppy](https://research.monash.edu/en/persons/graham-oppy)
    * [Hairong Qi](https://aicip.github.io/)
    * [Helen Seward](https://ahc.leeds.ac.uk/philosophy/staff/1167/professor-helen-steward)
    * [Isaac Wilhelm](https://isaacwilhelm.com)
    * [Jacob Barandes](https://www.jacobbarandes.com)
    * [John Norton](https://sites.pitt.edu/~jdnorton/jdnorton.html)
    * [Joseph Schmidt](https://josephschmid.com/research/)
    * [Justin Mooney](https://www.justinmooney.net)
    * [Kerry McKenzie](https://www.kerrymckenzie.org)
    * [Melanie Mitchell](https://melaniemitchell.me)
    * [Michael Heumer](https://spot.colorado.edu/~huemer/)
    * [Nick Bostrom](https://nickbostrom.com)
    * [Philip Goff](https://philipgoffphilosophy.com)
    * [Simono Friedrich](https://simonfriederich.eu/publications.html)
    * [Taylor Cyr](https://taylorwcyr.com)
    * [Thomas Metcalf](https://shc.academia.edu/ThomasMetcalf)
    * [Tim Oconor](https://sites.google.com/site/hildebtw/?pli=1)
    * [Tyler Hildebrand](https://sites.google.com/site/hildebtw/?pli=1)
* Places
    * [CERN](https://home.cern)
    * [ORNL](https://www.ornl.gov)
    * [SNS](https://neutrons.ornl.gov)
    * [UTK physics](https://physics.utk.edu)
* Physics journals
    * [Chaos](https://pubs.aip.org/aip/cha)
    * [Entropy](https://www.mdpi.com/journal/entropy)
    * [Nature](https://www.nature.com)
    * [PRAB](https://journals.aps.org/prab/)
    * [PRE](https://journals.aps.org/pre/)
    * [PRL](https://journals.aps.org/prl/)
    * [Science](https://www.science.org)
* Preprint servers
    * [ArXiv](https://arxiv.org)
    * [ArXiv (accelerator physics)](https://arxiv.org/list/physics.acc-ph/recent)
    * [ArXiv (astrophysics of galaxies)](https://arxiv.org/list/astro-ph.GA/recent)
    * [ArXiv (chaotic dynamics)](https://arxiv.org/list/nlin.CD/recent)
    * [ArXiv (computational physics)](https://arxiv.org/list/physics.comp-ph/recent)
    * [ArXiv (data analysis, statistics, and probability)](https://arxiv.org/list/physics.data-an/recent)
    * [ArXiv (history and philosophy of physics)](https://arxiv.org/list/physics.hist-ph/recent)
    * [PhilSci](http://philsci-archive.pitt.edu)
    * [philpeople.org](https://philpeople.org)
* [Bibliography on the problem of evil](https://docs.google.com/document/d/1dprquqrzQxJsmOArxEoBDaMx15T9T--P8dagUqX6kQI/edit#heading=h.x1uym8fk8fq3)
* [lesswrong](https://www.lesswrong.com)
* [Little debates](https://www.routledge.com/Little-Debates-about-Big-Questions/book-series/LDABQ)
* [Einstein papers](https://einsteinpapers.press.princeton.edu)
* [Probability theory as extended logic](https://bayes.wustl.edu)
* Articles
    * [Why academics stink at writing](https://www.chronicle.com/article/why-academics-stink-at-writing/)
    * [The preprint revolution](https://upstream.force11.org/the-preprint-revolution-implications-for-bibliographic-databases/)
    * [Runescape helps Venezuelans survive](https://www.polygon.com/features/2020/5/27/21265613/runescape-is-helping-venezuelans-survive)
    * [Zombie nouns](https://archive.nytimes.com/opinionator.blogs.nytimes.com/2012/07/23/zombie-nouns/)
    * [What is it like to be a philosopher?](http://www.whatisitliketobeaphilosopher.com)

