---
title: "*Stalin: Paradoxes of Power*"
author: Austin Hoover
date: 2025-12-07
categories:
    - books
    - history
---

*Stalin: Paradoxes of Power* is a history of Russia during Stalin's rise to power in the early 20th century. Part I describes the dramatic changes to the Russian tsarist autocracy in the lead-up to WWI. Stalin spends most of this time as a political exile in Siberia. Part II describes the sudden and violent rise of Lenin's Bolshevik government during the Russian revolution and civil war in 1917, during which Stalin positions himself as a key member of Lenin's inner circle. Part III describes Stalin's fight with Trotsky and others to consolidate power after Lenin's unexpected death. The book ends with Stalin's triumph over his political rivals and his unthinkable decision to force collectivization of the entire country in 1928.

This is an amazing book. It's less of a biography of Stalin than a comprehensive political history of Russia and Eurasia during the first half of Stalin's life. My favorite scene was Stalin's quiet return from exile on a train from Siberia in 1917. He enters a world in absolute chaos and emerges with enormous political authority through a combination of random chance and sheer force of will. The title, "paradoxes of power", refers to the increasingly difficult challenges Stalin faced as he accumulated power within the Bolshevik government; from Lenin's "Testament", a letter purportedly from Lenin calling for his removal, and from Trotsky, his bitter rival.

Also check out Kotkin's interviews with Peter Robinson ([part 1](https://www.youtube.com/watch?v=3MzPzfEVjNE), [part 2](https://www.youtube.com/watch?v=eZ9KCG0KO4U)).


## Part I: Double-Headed Eagle

> Stalin’s dictatorial regime presents daunting challenges of explanation." His power of life and death over every single person across eleven time zones—more than 200 million people at prewar peak—far exceeded anything wielded by tsarist Russia’s greatest autocrats. Such power cannot be discovered in the biography of the young Soso Jughashvili. [3]

> More than for any other historical figure, even Gandhi or Churchill, a biography of Stalin, as we shall see, eventually comes to approximate a history of the world. [4]

> World history is driven by geopolitics. [4]

> Stalin seems well known to us. An older image—that his father beat him; the Orthodox seminary oppressed him; he developed a "Lenin complex" to surpass his mentor, then studied up on Ivan the Terrible, all of which led to the slaughter of millions—has long been unconvincing, even in its sophisticated versions that combine analyses of Russian political culture and personality. [7]

> He devoured books, which, as a Marxist, he did so in order to change the world. [10]


### Chapter 1: An Imperial Son

> Over the more than four centuries from the time of Ivan the Terrible, Russia expanded an average of fifty square miles *per day*. [11]

> All the ad hoc empire building—and there is no other kind—resulted in a jumble of contradictions. [13]

> These immense geopolitical facts that accompanied Stalin’s birth and early life—a unified industrial Germany, a consolidated industrial Japan, an American power greater than any other in world history—would shake the tsarist regime to its core and, one day, confront Stalin, too. [19]

> Studying among the monks at the seminary, the future Stalin may have thought to become a monk himself. But changes in the Russian empire and in the wider world opened up a very different path. [28]


### Chapter 2: Lado’s Disciple

> Tiflis exuded a haunting, magical beauty. [29]

> By 1900, Tiflis had acquired a small but significant intelligentsia and a growing industrial worker class. It was in this modernizing urban milieu that Jughashvili—who was back in Tiflis as of 1894—entered the seminary and came of age, becoming not a priest but a Marxist and revolutionary. [30]

> A headstrong twenty-something militant, Vladimir "Lado" Ketskhoveli would serve as the revolutionary mentor for the future Stalin, who in looking back would call himself a disciple of Lado. [30]

> Under Lado’s influence, the young Jughashvili, already an energetic autodidact, found a lifelong calling in being an agitator and a teacher, helping the dark masses see the light about social injustice and a purported all-purpose remedy. [30]

> Later, Stalin would not erase Lado’s independent revolutionary exploits or existence, even as almost everyone else connected to the dictator at one time or another would be airbrushed. [55]


### Chapter 3: Tsarism’s Most Dangerous Enemy

> Russian Eurasia—104 nationalities speaking 146 languages, as enumerated in the 1897 census—was the world’s most spectacular kaleidoscope, but in truth, empire everywhere presented a crazy patchwork. [57]

> Peter’s method of state building also reinforced the circumstance whereby Russia’s elites remained joined at the hip to the autocratic power. [57]

> Unlike absolutism in Prussia, Austria, Britain, or France, Russia’s autocracy endured deep into modern times. [59]

> The inflexible autocracy had many enemies, including Iosif Jughashvili. But its most dangerous enemy was itself. [60

> Russia’s autocracy had undergone a near-death experience. Altogether, an army of nearly 300,000, a size close to the land force that had battled the Japanese, was needed to suppress domestic unrest. [86]

> Durnovo’s rescue of Russia’s autocracy—when it should have fallen—would end up having the perverse consequence of preparing the country for a far worse crash during a far worse war, which would serve as a template for a radical new order. [87]


### Chapter 4: Constitutional Autocracy

> Russia’s state had arisen out of military exigencies, in an extraordinarily challenging geopolitical environment, but also out of ideas, above all the autocratical idea, yet Russia’s long-enduring autocracy was anything but stable. [88]

> Stolypin was determined to take full advantage of the new lease on life afforded to the regime by Durnovo’s bravura crackdown, with the new situation created by Witte’s successful urging on Nicholas II of the October Manifesto quasi-constitutionalism. [92]

> Constitutional autocracy was self-defeating. [128]

> In international affairs, Stolypin had been unable to avoid a de facto posture of alignment with Britain against Germany. [129]

> A focus not on leftist revolutionary activity but on geopolitics and domestic high politics reveals the central truth about imperial Russia: The tsarist regime found itself bereft of a firm political base to meet its international competition challenges. [130]

> Of all the failures of Russia’s autocracy with regard to modernity, none would be as great as its failure at authoritarian mass politics. [130]

> Autocratic Russia’s discouragement of modern mass politics would leave the masses—and the profound, widespread yearning among the masses in Russia for social justice—to the leftists. [130]



## Part II: Durnovo’s Revolutionary War

> Between 1905 and 1911, revolutions broke out in Mexico, Qajar Iran, the Ottoman Empire, China, and Portugal, as well as Russia—countries that together accounted for one quarter of the earth’s population. Each led to the introduction of constitutions. [131]

> Socialism, concretely, meant a life in Siberia. [132]

> The analysis—an avoidable war against a too-powerful Germany; Russia’s defeat; Russian elites heedlessly pressuring the autocracy only to be engulfed by extreme social revolution—was as hard-boiled as it was blunt. Nothing penned by Vladimir Lenin, not even his later celebrated polemic *State and Revolution* (August 1917), approached the clairvoyance of Durnovo. [135]

> Nostalgia for tsarist Russia, however understandable, is misplaced. [137]

> For a Georgian from small-town Gori—via Tiflis, Chiatura, Backu, and Siberian exile—to rise anywhere near the summit of power, and seek to implement Marxist ideas, the whole world had to be brought crashing down. And it was. [137]

> To make sense of Stalin’s role in the sudden, stunning episode of 1917, and above all to understand his entire later regime, the momentous history in which he had little noteworthy part must be described and analyzed in depth. [138]

> Modern revolutions are spectacular events, awesome in the millions who rise up and stake a claim to control their destiny, exhilarating in their new solidarities and sense of unlimited possibility. But revolutions are also signs of decay and breakdown, the cracking of one ruling system and the untidy formation of another. [138]


### Chapter 5: Stupidity or Treason?

> Alliances by themselves never cause war; calculation and miscalculation do. [140]

> Germany was eager for the conflict in supposed self-defense against a weak Russia that was deemed on the brink of becoming invincible. [141]

> As the Ottoman Empire contracted, the other big land empires ground up against one another like tectonic plates, which is how the fault line of tiny Serbia precipitated a world war and, not the eastern front, a revolution in the Russian empire. [141]

> The conflict of August 1914 escalated into a world war partly because of the expectation that states were vulnerable to conquest, but it was protracted because of the circumstance that they were not. [149]

> Lenin added a politics of imitative war techniques to his Marxist ideology, which the wartime slaughterhouse helped to validate in ways that the prewar never did. [151]

> Revolutions are like earthquakes: they are always being predicted, and sometimes they come. Throughout 1916 and into early 1917, almost every branch of the *okhranka> was warning of pending revolution (as well as anti-Jewish pogroms). [164]

> Stalin—suddenly a free man, for the first time in nearly seventeen years—boarded the Trans-Diberian Railway bound for Petrograd. […] The future dictator arrived in the imperial capital on March 12, 1917, wearing Siberian *valenki* (felt boots) and carrying little more than a typewriter. [173]



### Chapter 6: Kalmyk Savior

> After tsarism’s coercive and corrupt rule, its narrow privilege and pervasive poverty, and above all its relentless denial of human dignity, hope for new horizons understandably soared. [174[

> Russia’s army would steamroll not Germany but the country’s own political system. [175]

> How "socialism" came to be Bolshevism, and how the Bolsheviks came to be Leninist, are separate questions. [176]

> After months of open discussion in newspapers, barracks, factories, street corners, and drawing rooms, the Bolshevik putsch was over and done before the vast majority of the population knew it had happened. [218]

> Trotsky cut an inordinately dashing figure—the shock of wild dark hair and blue eyes, the pince-nez of an intellectual, and the broad shoulders of Hercules—but he wielded his public charismatic power on behalf of Lenin. Lenin’s power was uncanny. [221]

> Stalin was one of the only two people who Lenin gave permission to enter his private apartment in Bolshevik headquarters at Smolny, a proximity and confidence that would prove pivotal. [226]


### Chapter 7: 1918: Dada and Lenin

> The Bolsheviks looked destined for oblivion. The would-be "regime" consisted, at the top, of just four people: Lenin, Trotsky, Sverdlov, and Stalin, each of whom had a criminal record for political offenses and none of whom had any administrative experience. [228]

> That such lowly beginnings would soon become one of the world’s strongest dictatorships is beyond fantastic. [229]

> Dada and Bolshevism arose out of the same historical conjuncture. [230]

> If the collapse of the tsarist order was a revolution, the revolution was a collapse. [230]

> The catastrophic collapse of the old world, however debilitating for millions of real people, was taken as progress by the Bolsheviks: the deeper the ruin, the better. [231]

> Bolshevism was a movement, a capacious, freewheeling, armed anarchy of sailors and street squads, factory hands, ink-stained scribes and agitators, would-be functionaries wielding wax seals. [232]

> Such was the Bolshevik monopoly in the stateless anarchy: idea factories, gun-toting drunks and marauding Red Guards, a deliberately shattered financial system, depleted food stocks, an ambiguous junior partnership for the Left SRs, and an ineffectual secret police busy with property theft and the very speculation it was supposed to combat. [242]

> Bolshevism’s core convictions about capitalism and class warfare were held to be so incontrovertible that any and all means up to lying and summary executions were seen as not just expedient but morally necessary. [268]


### Chapter 8: Class War and a Party-State

> The new state took shape by means of the predation, confiscation, and redistribution of material things, as well as the intimidation or conscription of people, refracted through notions of revolutionary class warfare. [289]

> Pitiless class warfare formed the core of Lenin’s thought, but a Soviet state was not born fully armed from Lenin’s forehead. [291]

> Whatever Versailles’ deep flaws in principle, it failed utterly in terms of power politics: the United States would go home, the British would back away, and the French—who shared a land border with Germany—could not bear the burden of enforcing the treaty provisions. [316]

> All during the cacophony of Versailles, the world was shifting, and it would shift still more, in ways that escaped the major protagonists: France, Britain, and the United States. [323]

> Trostsky liked to portray himself as above it all, as if politics in the Bolshevik regime did not involve constant backbiting and smearing. [329]

> Symbolically, a red-white binary—Bolsheviks against everyone else, including those who made the February Revolution and the non-Bolshevik socialists—defined the new regime. [338]

> Traditionally, "Traditionally, Russia’s civil war, even more than the October coup, has been seen as Trotsky’s time. […] But the facts do not bear out the long-held notion that Trotsky emerged significantly stronger than Stalin. [339]


### Chapter 9: Voyages of Discovery

> Kaleidoscopic does not begin to capture the civil war in Eurasia, particularly in the years 1920-1921. [345]

> Russia’s civil war amounted to a kind of "voyages of discovery", even if, unlike Christopher Columbus and Vasco da Gama, the voyagers did not cross literal oceans. [345]

> The unexpected significance of the national question in the civil war proved to be yet another issue that empowered Stalin, and brought him into a close working relationship with Lenin. [346]

> For Lenin, Poland as well as Crimea were of a piece—two toeholds for world imperialism, at the pinnacle of which he saw London. [360]

> No other civil war in history took place across such an immense expanse. [405]

> The victorious Soviet state had emerged victorious, penetrated. […] Durnovo’s revolutionary war had yielded a paradoxical outcome. [408]



## Part III: Collision

> He [Lenin] was a singular political figure. [409]

> Who does not know that the world history of all revolutions shows that class struggle turns not accidentally but inevitably to civil war? [Lenin] [409

> Once in power, Lenin elevated political violence to principle. […] Behind mundane disagreement he saw not legitimate opinion but malevolent forces. His conception of politics did not even allow for politics. [410]

> Rarely in world history has one man played such an outsized role and, suddenly, been sidelined—an outcome evocative, in very different political ways, of Abraham Lincoln’s civil war victory and emancipation of the slaves, followed by his assassination. Lenin’s early departure was an unintentional revolutionary shock second only to the seizure of power, and it unexpectedly cleared a path for Stalin to supreme power. [410]

> Few issues in Soviet history involved more intrigue than Lenin’s so-called Testament, which is dated to December 1922-January 1923, but which, as we shall see, Lenin might not have dictated at the time—contrary to entrenched scholarship—or even dictated at all. [418]

> Part III will examine Stalin’s creation of a personal dictatorship within the Bolshevik dictatorship, and the ways he put that remarkable power to use. [419]

> The personal dictatorship that Stalin painstakingly built, he would, beginning in January 1928, use to enact a vision of anti-capitalist socialism, utterly transforming and shattering Eurasia. [421]


### Chapter 10: Dictator

> But what stands out most about Stalin’s ascendancy is that, structurally, he was handed the possibility of a personal dictatorship, and he began to realize that potential just by fulfilling the duties of general secretary. Stalin had exceptional power almost instantaneously. [425]

> Naked careerism was one reason they sought to attach themselves to the general secretary, but many were attracted to Stalin because of his tenacious dedication to the revolutionary cause and to the state’s power. [427]

> Stalin returned again and again to the touchstone of Lenin’s writings. The fundamental fact about him was that he viewed the world through Marxism. [462]

> A very few people figured Stalin out early on. [464]

> Stalin could be very closed and inaccessible, yet he could also switch on the charm… [465]

> Thrust into power, Stalin found himself on a lifelong quest not only for personal glory but also for deciphering the secrets to ruling over men and things in order to further Russian power in the world. [469]

> Lots of regimes have a secret police and hunt for enemies. What differentiated this regime was its special single-party structure and a transcendent idea, the vision of a new world of abundance, social justice, and peace. [470]

> It was not Trotsky, let alone Zinoviev or Kamenev, but Stalin’s principal patron, Lenin—or at least, dictation attributed to Lenin—who would prove to be the gravest threat to the absolute power inherent in the general-secretary position, and to Stalin’s psychic balance. [471]


### Chapter 11: "Remove Stalin"

> But even as the means to build a dictatorship within the dictatorship within the dictatorship had fallen right into his hands, the most astonishing thing took place: Lenin appeared to call for Stalin’s removal. […] The key phrase—"remove Stalin"—would eventually haunt Soviet Eurasia and the world beyond, but in the first instance would haunt Stalin himself. [473]

> Trotsky persisted in his quest for economic dictatorship as a counter to Stalin’s party dictatorship."

> Lenin’s alleged "Notes" were dated December 30-31, 1922, and Fotiyeva later observed that the long article had been dictated in two fifteen-minute sessions. The typescript lacked a signature or initials."

> Trotsky’s appearance, amid blazing lights and rolling movie cameras, provoked a thunderous ovation. […] He delivered a long, intricate speech that introduced a brilliant metaphor to capture a major crisis bedeviling the regime’s economic policy. […] Stalin delivered a second report, on nationalities, and began unable to outdo Trotsky in the theatrics, concentrated on substance and delivered the speech of his career to that date. […] Stalin enjoyed a moment of high visibility and a smashing victory. Trotsky himself, by putting before the Party Congress the choice of Lenin’s authority versus his (Trotsky’s) on the matters of the New Economic Policy and the Union federation, had allowed Stalin to demonstrate that he was the one faithful to Lenin [495-496]

> "Comrade Stalie, having become general secretary, has concentrated boundless power in his hands, and I am not sure whether he will always be able to use that power with sufficient caution. [499]

> This alleged dictation—perhaps the most momentous document of the entire regime’s history until now—should have radicalized the political dynamic. But Zinoviev and Bukharin, in possession of knowledge of Lenin’s ostensible instruction to find a way to remove Stalin as general secretary, did not do so. [505]

> "Zinoviev's failure to act upon his own blatant ambition and force the issue of Stalin's removal---even more than Kamenev's hesitation merely to curb some of Stalin's powers---was arguably the most consequential action (or inaction) by a politburo member after Lenin had become irreversibly sidelined: [513]

> Trotsky exploded. He shot up, stated, "I request that you delete me from the list of actors of this humiliating comedy," and stomped out, resolving to slam the cast-iron door---a massive metal structure not given to demonstrative slamming. He could only manage to bring it to a close slowly, unwittingly demonstrating his impotence. Whether by design or dumb luck, Stalin, Zinoviev, and Kamenev had humiliated Trotsky. [516]

> "Bolshevism itself was nothing if not a faction, a minority, which, back in 1903, had broken off and called itself majoritarians (Bolsheviks) while tagging its opponents as minoritarians (Mensheviks) [519]

> Trotsky united instead of divided his enemies with a relentlessly condescending personality. By nature aloof as well, he was clueless about the consequences, even in hindsight, as when he would recall that he had refused to socialize with others in the ruling group because he "hated to inflict such boredom on myself. The visiting of each other’s homes, the assiduous attendance at the ballet, the drinking-parties at which people who were absent were pulled to pieces, had no attraction for me… It was for this reason that many group conversations would stop the moment I appeared. [520]

> The Bolshevik regime was suffocating the country and itself in paperwork and red tape, presiding over mass embezzlement amid impoverishment, hostile to, yet dependent upon, the market, fearful not only of peasants’ political leanings but of works’ as well. Inside the roiling mess, however, Stalin was building a personal dictatorship. [527]

> Direct evidence of Stalin’s emotional state in 1922-23 is slight. [528]


### Chapter 12: Faithful Pupil

> Such were the paradoxes of Stalin’s vertiginous ascent: he had "boundless power" early, from spring 1922, when appointed general secretary of the party and the next month Lenin suffered his first major stroke, but only one year later, in spring 1923, out popped a sheet of paper calling for Stalin’s removal. [530]

> The revolution’s predicament and Stalin’s personality began to reinforce each other, and form into a kind of Mobius strip under the pressure exerted by the Lenin dictation. [530]

> Trotsky did not seem to comprehend that his relationship to Lenin was a question not of fact but of positioning. [531]

> Stalin walked into a golden opportunity to become the orthodox Leninist as well as a household name by battling, and besting, the world-renowned Trotsky. [532]

> As Lenin’s would-be faithful pupil, Stalin emerged in 1924-25 as both an ideologue and an embryonic geostrategic thinker. [532]

> Stalin relished demonstrating his superior leadership skills with people, not least because the others at the top viewed him as inferior. [569]

> Probably no one despised Trotsky more than Voroshilov, not even Stalin himself, but the Voroshilov-Tukhachevaky animosity would reach operatic proportions. [576]

> In Trotsky’s mind Stalin was a deformation conjured into being by "the tired radicals, by the bureaucrats, by the NEPmen, the kulaks, the upstarts, the sneaks, by all the worms that are crawling out of the upturned soil of the manured revolution. [591]

> Stalin emerged a victor with a grudge, roiling with self-pity, resentment, victimhood. [591]


### Chapter 13: Triumphant Debacle

> Even Stalin’s absolute power did not delight him absolutely. He was thrilled being the center of attention, the decision maker, the leader, but it ate at him that everyone knew Lenin’s Testament called for his removal. The giddy pleasure of the torment, the king-held ambition and the current burden, the paradoxes of his power, weighed on him. [595]

> One gets the feeling that if Stalin could have stayed the whole year at Sochi, running the regime from there, he might have been content. [601]

> Thus did Stalin not only neutralize their main weapon—the damned Testament—he flagellated them with it. [607]

> What Stalin saw in the United States is not hard to grasp: America’s share of global production would soon reach a breathtaking one third."

> Trotsky, Zinoviev, and Kamenev had belatedly formed what they called the United opposition... [614]

> Trotsky rose, turned to the Georgian, pointed his finger and exclaimed, "The first secretary poses his candidacy to the post of grave digger of the revolution!" Stalin flushed with anger and fled the room, slamming the door. The session broke up in uproar. [615]

> Lenin had taught that capitalism would be weakened, perhaps fatally, if it could be cut off from its colonial and semi colonial territories, from which it extracted cheap labor, raw materials, and markets. [625]

> Ideologically, Leninism conflated anti-imperialism with anticapitalism, but many Chinese intellectuals, including those who had become Marxists, concluded that the depredations China suffered at the hands of foreign powers made anti-imperialism the bedrock task. [627]

> No one compelled Stalin to submit his resignation time and time again. […] What was this, the expression of a deep well of resentment? The voicing of his darkest fears, his removal by the Central Committee? A provocative test of the inner regime? An odd way that Stalin savored his triumph and the opposition’s expulsion? A gesture of false modesty by a man who treasured posing as the humble, albeit indispensable, servant of the party? It was perhaps all of the above—supremacy and siege, elation and self-pity, the paradoxes of Stalin’s power. [659]

> "At the present time, the task of transformation and amalgamation of small individual farms into large-scale collective farms must be set as the party’s fundamental task in the countryside." Collectivization, *at the present time*? The transcript records "Noise in the hall" when the amendment was read. [660]


### Chapter 14: A trip to Siberia

> Stalin boarded a heavily guarded train bound for Siberia. It was Sunday, January 16, 1928. […] In Novosibirsk, at gatherings with the local higher-ups, Stalin would demand coercive measures to overcome a state grain procurement crisis. He would also declare, unexpectedly, the inescapability of pushing forward the collectivization of agriculture immediately. [661]

> Modern Russian power, in its Soviet guise, too, still rested upon wheat and rye. [662]

> Stalin lived immersed in the grim OGPU summaries of the country’s political mood, which his worldview shaped in a feedback loop, and which brimmed with anti regime quotations from eavesdropped conversations and other reminders that the USSR was encircled by hostile forces and honeycombed with internal enemies. [668]

> Scholarly arguments that "no plan" existed to collectivize Soviet Eurasia are utterly beside the point. No plane *could* have existed because actually staining near complete collectivization was, at the time, unimaginable in practical terms." Collectivize one sixth of the earth? How? [675]

> Nothing had ever erupted in the Soviet Union quite like the spectacle of the Shakhty trial, which opened on May 18, 1928, in the marble-walled Hall of Columns of the House of Trade Unions and lasted forty-one days. [702]

> Stalin was about to make the most aggressive leftist speech of his life. […] Stalin again outlined a stirring vision of an immediate, wholesale agricultural modernization to large-scale farms—not of the individual kulak variety, but collectivized. [706]

> Stalin’s momentous turn to force collectivization and rapid industrialization became centered upon a drawn-out, painstakingly assistive humiliation of Bukharin. [718]

> Stalin’s malevolence was palpable. [719]

> Stalin lived in his world. [721]

> Bukharin predicted that total elimination of the market alongside forced collectivization of the peasantry would produce unfathomable red tape, overwhelming the party. Of the industrialization "plan", Bukharin mockingly wrote that "it is not possible to build present-day factories with future bricks. [722]

> We’ll call you organizers of famine. [723]


## Coda: If Stalin Had Died

> He would do it. Stalin would force the collectivization of Soviet villages and nomadic steppes inhabited by more than 100 million people between 1928 and 19333, a story taken up in volume II. [724]

> Countrywide, nearly 40 million people would suffer severe hunger or starvation and between 5 and 7 million people would die in the horrific famine, whose existence the regime denied. [724]

> Scholars who argue that Stalin’s collectivization was necessary in order to force a peasant country into the modern era are dead wrong. [724]

> Nor was the collectivization necessary to sustain a dictatorship. Private capital and dictatorship are fully compatible. [725]

> Nor did the adverse turn in the world economy compel collectivization. [726]

> If Stalin had died, the likelihood of forced wholesale collectivization would have been near zero and the likelihood that the Soviet regime would have been transformed into something else or fallen apart would have been high. [739]

> History, for better or for worse, is made by people who never give up. [739]

