---
title: "Longitudinal space charge forces in long bunches"
author: Austin Hoover
date: 2026-02-19
categories:
  - accelerators
  - space charge
---

These notes calculate the longitudinal electric field of a long bunch within a perfectly conducting cylindrical boundary. Following [Ferrario, Migliorati, and Palumbo](https://cds.cern.ch/record/1982426/files/331-356%20Ferrario.pdf).


## General expression of the field 

Start by applying [Faraday's Law](https://en.wikipedia.org/wiki/Faraday%27s_law_of_induction), which relates the curl of the electric field to the time derivative of the magnetic field.

$$
\nabla \times \mathbf{E} = -\frac{\partial \mathbf{B}}{\partial t}.
$${#eq-x}

In integral form, Faraday's law relates the "electromotive force" around a closed loop to the change in magnetic flux through the loop:

$$
\oint \mathbf{E} \cdot d\mathbf{l} = - \frac{\partial}{\partial t} \oint \mathbf{B} \cdot d\mathbf{A}.
$${#eq-x}

Choose a rectangular loop with one edge running parallel to the beam for a distance $\Delta z$ at radius $r$, and the opposite edge at radius $b$ (at the pipe boundary). For a long, axially symmetric charge distribution, Faraday's law gives

$$
\left( E_z(r, z) - E_z(b, z) \right) \Delta z
+ \int_{r}^{b} \left( E_r(r, z + \Delta z) - E_r(r, z) \right) dr
= -\Delta z \frac{\partial}{\partial t} \int_{r}^{b} B_\phi(r) dr.
$${#eq-integral}

Taking the limit $\Delta z \rightarrow 0$, we can define

$$
\frac{\partial E_r(r, z)}{\partial z} = \frac{E_r(r, z + \Delta z) - E_r(r, z)}{\Delta z}.
$${#eq-deriv}

Substituting @eq-deriv into @eq-integral gives

$$
E_z(r, z) = E_z(b, z) - \int_{r}^{b} \left( \frac{\partial E_r(r, z)}{\partial z} + \frac{\partial B_\phi(r, z)}{\partial t} \right) dr .
$${#eq-efield-long}

@eq-efield-long relates the longitudinal electric field at radius $r$ to the longitudinal field at radius $b$ (the pipe boundary), as well as the averaged *transverse* electric and magnetic fields between $r$ and $b$.

Let's do a bit more work to simplify this expression. First define $z = -\beta c t$, where $c$ is the speed of light, so that $\partial / \partial t = -\beta c \partial / \partial z$ and

$$
E_z(r, z) = E_z(b, z) - \frac{\partial}{\partial z} \int_{r}^{b} \left( E_r(r, z) - \beta c B_\phi(r, z) \right) dr .
$${#eq-efield-z-deriv}

Next, relate $B_\phi$ to $E_r$:

$$
B_\phi(r, z) = \frac{\beta}{c} E_r(r, z).
$$

@eq-efield-z-deriv simplifies to

$$
E_z(r, z) = E_z(b, z) - \frac{1}{\gamma^2} \frac{\partial}{\partial z} \int_{r}^{b} E_r(r, z) dr ,
$${#eq-efield-almost-final}

where $\gamma = (1 - \beta^2)^{-1/2}$ is the Lorentz factor. Finally, since the boundary at $r = b$ is perfectly conducting, $E_z(b, z) = 0$ and

$$
E_z(r, z) = - \frac{1}{\gamma^2} \frac{\partial}{\partial z} \int_{r}^{b} E_r(r, z) dr ,
$${#eq-efield-final}







## Exact formula for uniform transverse density

To calculate the longitudinal field $E_z(r, z)$ in @eq-efield-final, we first need to calculate the transverse field $E_r(r, z)$ and then average the field over the radial coordinate. We could do this numerically by solving the two-dimensional Poisson equation within each $z$ slice. But there's a special case that admits an exact solution.

Assume the bunch has line-charge density $\lambda(r, z)$ [C / m]. As long as the density varies slowly along $z$, we can approximate the electric field at fixed $z$ as purely transverse, i.e., generated by a set of infinite line charges (threads). We'll apply [Gauss's Law](https://en.wikipedia.org/wiki/Gauss%27s_law) to relate the charge density to the field. Gauss's Law says that the electric flux through a closed surface is proportional to the charge enclosed by the surface:

$$
\oint \mathbf{E} \cdot d\mathbf{A} = Q_{enc} / \epsilon_0 .
$${#eq-x}

Choose the surface to be a cylinder of radius $r$ and length $\ell$.

$$
\begin{align}
E_r(r, z) \cdot 2 \pi r l &= \frac{\lambda(r, z) l}{\epsilon_0} , \\
E_r(r, z) &= \frac{\lambda(r, z)}{2 \pi \epsilon_0 r} . \\
\end{align}
$${#eq-x}


Substituting into @eq-efield-final gives
$$
E_z(r, z) = - \frac{1}{\gamma^2} \frac{\partial}{\partial z} \int_{r}^{b} \frac{\lambda(r, z)}{2 \pi \epsilon_0 r} dr ,
$${#eq-x1}

Note that the field scales inversely with $\gamma^2$, so it vanishes at high energies. (This is maybe less intuitive than the transverse case.)

The integral in @eq-x1 can be evaluated exactly if the transverse density is uniform within radius $r$ and zero outside:

$$
\lambda(r, z) = \lambda_0(z) (r / a)^2.
$${#eq-x}

Note that $\lambda$ is the *line density*, which is nonzero at $r > a$. The transverse field becomes

$$
\begin{numcases} {E_r(r, z)=}
  \dfrac{\lambda_0(z)}{2 \pi \epsilon_0 a^2} r, & $r \le a$ \\\\
  \dfrac{\lambda_0(z)}{2 \pi \epsilon_0 r  }  , & $r \ge a$.
\end{numcases}
$${#eq-x}

The radial averaging gives a field proportaionl to the density gradient: 

$$
\begin{align}
E_z(r, z) 
&= -\frac{1}{4 \pi \epsilon_0 \gamma^2} \left[ 1 - \frac{r^2}{a^2} + 2 \ln{(b / a)} \right] \frac{\partial \lambda_0(z)}{\partial z} \\
&= -\frac{g(r)}{4 \pi \epsilon_0 \gamma^2} \frac{\partial \lambda_0(z)}{\partial z},
\end{align}
$${#eq-x}

where $g(r; a, b)$ captures the dependence on the transverse distribution:

$$
g(r; a, b) = 1 - \frac{r^2}{a^2} + 2 \ln{(b / a)}
$$

This model of longitudinal space charge is often called a *g-factor model*. It can be a good model in accelerator rings, where bunches are typically very long compared to the transverse dimensions.
