---
title: "Frank Sacherer: physicist and climber"
author: Austin Hoover
date: 2026-03-29
categories:
  - people
---

I found this [long thread](http://www.supertopo.com/climbing/thread.php?topic_id=268647&tn=0&mr=0) on Frank Sacherer, an accelerator physicist at LBNL and CERN in the 1960s and 70s. Sacherer is known in the accelerator physics community for publishing foundational work on space charge, collective effects, and stochastic cooling. (I knew his work from his [proof](https://www.osti.gov/servlets/purl/877342) that no ellipsoidally symmetric six-dimensional distribution projects to a uniform density in three dimensions.) But he’s also apparently a legend in the free-climbing community for pioneering routes in Yosemite, mostly on weekends during his PhD. He died at the age of 38 while climbing in the Swiss Alps.

The thread starts with a bunch of climbing stories from people who crossed his path in Yosemite. Eventually his ex-wife (Jan) joins and shares about his upbringing, personality, and their relationship. He was clearly extremely driven and talented, both in physics and climbing, and his intellectual life extended beyond physics into philosophy and ethics. On the other hand, he seems to have had several moral deficiencies, most notably a bad temper. The posts by Jan explain how his social, economic, and religious background shaped his psychology, but it’s still not entirely clear what motivated him to push so hard in his various pursuits, to the point of neglecting his close personal relationships. The whole thing was kind of sad to read and reminded me not to overvalue my own professional accomplishments.

Anyway, sometimes you read a series of papers by an author and feel like you learn something about their personality through their writing. But academic papers are so bland that it's hard to learn much, so I appreciated this look behind the scenes. Some quotes below:

---

On physics and climbing:

> It's difficult to try to explain Frank to climbers, since I knew him primarily in his intellectual and academic mode. He did severe climbing before I met him and after I departed, but hardly climbed at all during the time we were together. Nor did he want me to climb which was a source of great personal frustration. It's true that in the spring of 1965, he was told by his thesis advisor that if he took off one more summer to go to Yosemite, he would be dropped from the graduate program. Still, that doesn’t explain why he didn’t even want to do easy rock climbs on the weekends and turned every attempt of mine at climbing with him into a nightmare. Somehow it was all or nothing as far as climbing in the Valley went, although he did not at all mind starting from the beginning with snow and ice climbing when we got to the Alps. There we did do a lot of climbing together on safe classic routes like Mt. Blanc and the Matterhorn and with a minimum of personal friction.
>
> The other problem in explaining Frank is that physicists live in a different world than the rest of us. While Frank did use physics to figure out crack climbing techniques, (bordering on engineering is probably how he would have referred to it), most of his work was extremely abstract. Like many physicists and mathematicians he was a right brain thinker. The right brain is the center of symbols, strong emotions, and athleticism among other things, the very things at which he excelled. He was able to translate symbols into words however, only with great difficulty. He called people names and obscenities I believe, from lack of a more standard social vocabulary.
> 
> This sounds unbelievable given his intelligence unless you know the world he worked in. Often he would pace back and forth and mutter things like "it's coming, it's coming" and couldn't explain what, except that it had something to do with physics. Weeks later he would begin to put it down in mathematics, but still couldn't explain it in English. I remember one equation that went on for 30 finely written pages, but it was months before he could begin to formulate it in words. Then when we were in Europe, he would agonize for half a day over a simple one paragraph letter to his parents.
> 
> He was also very shy about telling you what he knew unless he felt very comfortable around you. He was great at explaining physics principles and philosophy without the use of mathematics to me, but resisted the idea of talking about it with anyone else. Physics was by no means his only intellectual interest. His 16 years of Jesuit schooling meant he had a wonderful classical education. When we went to Europe, we spent 10 months living in a Volkswagen bus and touring Europe. We visited every major museum, cathedral, and archaeological site in Greece and western Europe. We bought the Guides Bleus series of guidebooks and read through them word by word as we walked through these sites inch by inch, sculpture by sculpture, painting by painting. It was quite impressive to see him read on sight the original inscriptions in Greek and Latin at places like Thermopylae and Rome and then translate them almost simultaneously.
> 
> The question for all of us who knew him I suppose, is who was the real Frank? Or better yet, why wasn’t he better balanced so that he could enjoy both worlds at the same time without going from one extreme to the other? It is certainly a characteristic of the right brain thought process to focus intensely on a single subject at a time. I also have a few psychological theories concerning his religious and working class background as part of his conflicted view of the world. Still, after living with him for almost seven years, he remains even to me, a kind of enigma.



On ethics, religion, and gender roles:

> Pat, my old friend and climbing buddy from the days before I met Frank, thank you for your observations. Frank loved Colorado the two summers we visited there and enjoyed meeting my old friends. Given that all three of us were always intuitive types, yes there was a special rapport.
> 
> One subject often discussed in connection with Frank is religion. I think his 16 years of Catholic education had a big impact, but not in the ways that are generally thought. I never sensed that he worried over dogma or going to church which he never did. He had been through that a decade or more before I knew him. Certainly he never would have been found cursing against God as Roper has postulated in his portrayal of Frank for Camp 4, as Frank never entertained such a narrow and anthropomorphic concept of God. He was well aware of the mystical leanings of many great physicists and the philosophical questions posed by quantum mechanics and astronomy. He also knew a lot about Eastern philosophy and we often discussed the concepts which later appeared in The Tao of Physics.
> 
> Frank also had a rock solid sense of personal ethics from his religious background and a social conscience. Consequently we were both active in anti-Vietnam war activities in Berkeley. Of course every thinking person was involved somehow, though the Catholic Church as a generally conservative force, supported the war in the early days. Frank of course put personal conscience above the church. Luckily, Franks’s research assistantship at the Lawrence Radiation Lab exempted him from the draft.
> 
> One aspect of the 1960’s that Frank did not approve of was the drug taking. While I’m more the experimental type, Frank was dead set against any of it. I think this had to do with personal control issues however, rather than religion. Knowing Frank’s fondness for sweets, some of our friends did take it on themselves to dope some brownies once at a private slide show. I was not told of the scheme and not surprised when Frank ate several. I only caught on as we drove home and he began waxing ecstatically about the beautiful colors of the traffic lights. Much to the disappointment of our well-intentioned friends, getting Frank stoned did nothing to loosen him up. We were both agreed moreover, that this violated his free will, a basic principle of most religions, and the result was, we were very careful after that what we ate at parties.
> 
> The harmful effects of Frank’s Jesuit education were much more subtle. From my point of view, the worst thing he was taught, was the idea that compromise was the deadliest sin of all. As Ed has already noted, physicists like certainty and there is a certainty to climbing as well. Unfortunately when applied to human relationships, the results are not nearly so beneficial nor the right way of doing things so obvious. Most of the important interpersonal issues in life benefit from love, not logic. And for sure, there is more than one ideal way to get things done in the kitchen! Of course that never stopped Frank from trying to supervise even the smallest details.
> 
> The traditional Catholic view of women as either madonnas or whores probably caused our relationship the most damage however, as I never identified with either. This combined with Frank’s view of women’s proper roles based on his working class background, and the fact that he had no sisters, was something we were never able to overcome. In fact, the more I spoiled him with domesticity, the more he resisted my efforts to be a person in my own right. Looking back, I probably should have been more traditional in the sense of resorting to tears and throwing things, rather than trying to use logic on him. Arguing logically with a genius trained by Jesuits is 99% of the time a losing proposition, I can assure you.
> 
> Finally, he seemed to have imbibed a masochistic view of the world based on what the Jesuits taught him. He had the definite sense that one should not enjoy oneself too much as an equal amount of pain awaited, since everything must balance out. Of course, this may just have been his interpretation of what he was taught by the church, plus a good dose of what he knew from solving physics equations. His masochism did however, give him tremendous drive and discipline. He was the first climber to systematically work out at circuit training. I ran the circuit too, when training for specific outings, but only Eric Beck eventually joined him for regular workouts – discipline for its own sake. The discipline I learned from Frank did have a major effect on my own life however, when applied to academia. I owe much of my own subsequent success to his influence, even though he did his best to thwart my efforts along these lines, while we still lived together.
> 
> As for my friend Dick Erb's comments about Frank saying he would quit climbing if he ever found the perfect woman, all I can say is that if he ever thought it was me, he had a hell of a way of showing it!




On social class:

> I believe that another source of Frank’s internal conflicts came from the distance he had traveled from his original social background. His mother graduated from high school and his father barely made it out of the 8th grade. His father was a member of the teamster’s union and spent his life delivering baked goods to groceries stores around the Bay Area as did his younger brother. Sociologists tell us that even changing up or down one social class is stressful and can result in cognitive dissonance. How much more so if you are the first in your family to go to university and you end up getting a Ph.D. in theoretical physics, your thesis signed by a Nobel prize winner?
> 
> Frank was not an easy child for working class parents to deal with either. They suffered through many youthful pranks, like his rewiring the front door bell to drive them crazy with ringing and no one there. It took an electrician to figure that one out. Their most serious concerns came however, in the 1950’s, with his home- made rocket building activity. Fearing he would actually get one to launch from their backyard in San Francisco, they worried about liability. Frank's father then helped him launch his rockets in the forest up on Mt. Davidson in San Francisco, figuring that if he set the woods on fire, they could both run and the city would be responsible! Frank was said to be like his paternal grandfather who was a skilled machinist and inventor of many mechanical gadgets some still used in the wheelhouse of the San Francisco Cable cars.
> 
> Frank's parents also didn't want him to climb because of the danger of course, and several times told of their anguish when the hospital in Yosemite phoned them after the 80' leader fall. They were very happy when he got married and stopped all that. I'm not sure if they had heard the prediction that he would not live to be 30, but were devastated when he was killed as they didn't even know that he had taken up climbing again. I was shocked for the same reason as I thought having gotten him through age 30 alive, and because of his avowals to never get involved in serious ice climbing, that he was safe.
> 
> Frank’s father also did not want him to be a physicist and preferred him to become an engineer instead. In his father’s eyes, engineers were normal, while he didn’t want his son to grow up “weird like Einstein”. Of course this became a joke between us, and from time to time I teased him that he was becoming just as nutty as that great scientist.
> 
> Frank's parents were very loving and supportive of both of us. The problem was that they just couldn't understand us and our life most of the time. Sometimes they were bemused, other times totally mystified. Because of this, I think Frank paid a high price psychologically, for his intellectual and social mobility.



On his death in the Alps:

> I have been thinking about Tom Cochrane’s comments for a couple of days now along with some new information I have received in emails from various people who knew Frank in Europe.
> 
> At one level I am inclined to say that we should not take dramatic statements from Frank at face value. Even though he once told Dick Erb that he hated physics that obviously wasn’t true. Likewise I am skeptical of him being scared to death of climbing.
> 
> On the other hand, all the concern about courage which Tom describes, would fit with Frank’s classical education and his selection of Achilles as his role model, along with the ideal that it was better to go out in a blaze of glory than live a long life of no particular achievement. I simply don’t know because Frank never talked about his climbing career in terms of accomplishment. Occasionally he would relate an entertaining story about someone or something that happened on a particular climb, but I never once heard him speak about why he climbed or his climbing record.
> 
> Whatever Frank did, it was with great intensity, including not climbing. When he quit he never looked back and hated my attempts to have enjoyable afternoons together on the rock. Maybe he did feel that if it wasn’t challenging enough to be scary, it wasn’t worth doing? I always assumed that people climbed because they enjoyed it and can see in retrospect that not understanding each others motives for climbing could have been a large part of our personal dissonance on the rock. I also feel quite sure in retrospect, that finding Jim Baldwin after his fatal fall affected Frank deeply, and probably played a large role in his decision to stop climbing. All those predictions that he would not live to be 30, no doubt became more real to him when someone he knew died.
> 
> During our time together in Europe, Frank did achieve what Tom wished for him – the enjoyment of his skills in the mountains with no drama or struggle. I feel certain that he never mentioned his American climbing career to his European friends, because he didn’t want to be the object of any expectations. Evidently this continued for a few years but changed somehow, with the arrival in CERN of American ice climbers John Randle and Joe Weis. John has told me that Frank was out of shape and depressed about the bourgeois life when he arrived in Geneva, so the desire for good friends from his own culture was part of it, but boredom and lack of challenge also. Once climbing in a new medium, overcoming fear might well have been part of the attraction.
> 
> Frank loathed the cold and suffered greatly from it because he was so thin. The very physical quality that helped him succeed in the Valley crack systems meant that unless constantly moving about, he would sink to the bottom of every body of water we swam in, and he always become chilled before I did. A man more unsuited to overnight alpine bivouacs could not be found. However, he might have decided with perfect Jesuit logic that it was time to endure some suffering for a change, as he had become too soft. He did subscribe to their idea that pleasure and pain in life should even out, that the goal was to be neutral. Once set on the ice climbing path, it seems possible that he waged a new battle - over both discomfort and fear.
> 
> I have recently learned that after John Randle declined to climb the Shroud thinking it too late in the season, Frank told his office mate at CERN that he didn’t want to go either, that he also had a bad feeling about it, but didn’t want to let Joe Weis down. For Joe it was supposed to be his final severe climb as he knew already that his wife was two months’ pregnant. He had promised her that after this one final extreme climb he would only do safe, moderate routes because of the baby. Klara herself had a dream the night before they left, that Joe would be killed and begged him not to go. Their departure was delayed on the approach day because of her many attempts to dissuade them. Still, they went. Joe had checked the weather and it was supposed to hold.
> 
> I look at the photos of the final hours of the climb posted by John, especially the one of Frank in the morning after the snow shelf bivouac, and he looks to me to already be in trouble, in a kind of hypothermic and perhaps hypoglycemic haze. I have also learned that when they were found, Frank was wearing both his and Joe’s parka. Pratt’s comments to Cochrane, “He can’t handle a bivouac…….and can’t climb worth a darn the next day”, come back to haunt. Frank’s preference for minimalism in food and clothing also gives pause for thought.
> 
> We can only stand in awe of a climbing partner like Joe who would give up his own parka in the middle of a snow storm to help his friend, and from this we can also surmise that the situation was already quite desperate. I feel that Frank’s cold intolerance was probably the reason they decided to try to descend quickly via the Hirondelles route rather than go to the top in the midst of snow and lightning and then down the longer Italian descent.
> 
> It seems likely that neither was thinking very clearly as all of their safety gear was in Frank’s pack, including their prussic slings. In the interests of speed they had brought along only one pair. They were off route and according to the Chamonix rescue service, already on their way to a fatal rappel off the north face when Frank fell. Perhaps he passed out first or lightning was a factor. In either case, they died tied together, Frank instantly while wearing two parkas, and Joe in only a thin windbreaker, unable to go up or down, stuck on an icy rope with only one ice axe and no prussics.
> 
> Meanwhile, Frank’s motives for being up on a route unsuited to his preferences and physiology remain obscure. Was it self discipline, the desire to overcome an old fear, or friendship and obligation? We will never know. It’s possible that his second career of extreme climbing had entirely different motivations than his first. He was a complicated man and even to those close to him, remains a mystery.



Links:

* <http://www.supertopo.com/climbing/thread.php?topic_id=268647&tn=0&mr=0>
* <https://www.osti.gov/servlets/purl/877342>
* <https://aip.brightspotcdn.com/PTO.v32.i2.69_1.online.pdf>
* <https://www.nytimes.com/2001/02/20/science/a-passion-for-physical-realms-minute-and-massive.html?searchResultPosition=1> (paywall)