---
title: "N-dimensional MENT via particle sampling"
date: 2024-10-07
author: Austin Hoover
categories:
  - entropy
  - tomography
  - mcmc
bibliography: references.bib
csl: ./american-physics-society.csl
toc: false
draft: true
---

[Summarize https://arxiv.org/pdf/2409.17915.]

This [preprint](https://arxiv.org/pdf/2409.17915) describes a new approach to [MENT]() which should scale to N dimensions. MENT updates a prior distribution $q(x)$ to a posterior $p(x)$ compatible with a set of constraints $\{ G_i[p(x)] = 0 \}$ by maximizing the relative entropy $S[p(x), q(x)]$. The relative entropy is defined as

\begin{equation}
S[p(x), q(x)] = \int{p(x) \log{\frac{p(x)}{q(x)}} dx}.
\end{equation}

THe constraints are projections of the distribution onto lower-dimensional planes. The integration lines need not be straight. We write the integrals as straight-line projections of the transformed coordinates

\begin{equation}
u_i(x) = \mathcal{M}_i(x),
\end{equation}

with transfer map $\mathcal{M}_i: \mathbb{R}^N \rightarrow \mathbb{R}^N$. This give 

\begin{equation}
G_i[p(x)] = \int \rho(u_{i_\parallel}(x) du_{i_\perp}).
\end{equation}


MENT updates a prior distribution $q(x)$ to a posterior $p(x)$ by maximizing the relative entropy::

\begin{equation}
S[p(x), q(x)] = \int{p(x) \log{\frac{p(x)}{q(x)}} dx},
\end{equation} 

where $x = [x_1, \dots, x_N]^T$,  

subject to a set of constraints. The constraints are projections of the distribution onto 
