---
title: "Solzhenitsyn: And the next day"
date: 2026-06-22
date-modified: 2026-06-22
categories:
  - books
  - history
  - Russia
---

From *The Gulag Archipelago (Volume 2)*:

> And the next day that fine drizzle kept falling and falling. The clay pit had got drenched, and we were struck in it but good. No matter how much clay you took on your spade, and no matter how much you banged it on the side of the truck, the clay would not drop off. And each time we had to reach over and push the clay off the spade into the car. And then we realized that we had been merely doing extra work. We put aside the spades and began simply to gather up the squelching clay from under our feet and toss it into the car.
>
> Borya was coughing. There was still a fragment of German tank shell in his lungs. He was thin and yellow, and his nose, ears, and the bones of his face had grown deathly pointed. I looked at him closely, and I was not sure: would he make it through a winter in camp?
>
> We still tried to divert our minds and conquer our situation---with thought. But by then neither philosophy nor literature was there. Even our hands became heavy, like spades, and hung down.
>
> Boris suggested: “No, to talk… takes much strength. Let’s be silent and think to some purpose. For example, compose verses. In our heads.”
>
> I shuddered. He could write verses here and now? The canopy of death hung over him, but the canopy of such a stubborn talent hung over his yellow forehead too.
>
> And so we kept silent and scooped up the clay with our hands. The rain kept coming. Yet they not only didn’t take us out of the clay pit, but Matronina, brandishing the fiery sword of her gaze (her “red” head was covered with a dark shawl), pointed out to the brigadier from the edge the different ends of the clay pit. And we understood: they were not going to pull out the brigade at the end of its shift at 2 PM, but would keep it in the clay pit until it fulfilled its norm. Only then would we get both lunch and dinner.
>
> In Moscow, the construction project was halted for lack of bricks.
>
> But Matronina departed and the rain thickened. Light red puddles formed everywhere in the clay and in our car too. The tops of our boots turned red, and our coats were covered with red spots. Our hands had grown numb from the cold clay, and by this time they couldn’t even through anything in the car. And then we left this futile occupation, climbed up higher to the grass, sat down there, bent our heads, and pulled the collars of our coats up over the backs of our necks.
>
> From the side we looked like two reddish stones in the field.
>
> Somewhere young men of our age were studying at the Sorbonne or at Oxford, playing tennis during their ample hours of relaxation, arguing about the problems of the world in student cafes. They were already begin published and were exhibiting their paintings. They were twisting and turning to find ways of distorting the insufficiently original world around them in some new way. They railed against the classics for exhausting all the subjects and themes. They railed at their own governments and their own reactionaries who did not want to comprehend and adopt the advanced experience of the Soviet Union. They recorded interviews through the microphones of radio reporters, listening all the time to their own voices and coquettishly elucidating what they wished to say in their last or their first book. They judged everything in the world with self-assurance, but particularly the prosperity and higher justice of our country. Only at some point in their old age, in the course of compiling encyclopedias, would they notice with astonishment that they could not find any worthy Russian names for our letters---for all the letters of our alphabet.
>
> The rain drummed on the back of our heads, and the chill crept up our wet backs.
>
> We looked about us. The half-loaded cars had been overturned. Everyone had left. There was no one in the entire clay pit, nor in the entire field beyond the compound. Out in the gray curtain of rain lay the hidden village, and even the roosters had hidden in a dry place.
>
> We, too, picked up our spades, so that no one would steal them---they were registered in our names. And dragging them behind us like heavy wheelbarrows, we went around Matronina’s plant beneath the shed where empty galleries wound all around the Hoffmann kilns that fired the bricks. There were drafts here and it was cold, but it was also dry. We pushed ourselves down into the dust beneath the brick archway and sat there. 
Not far away from us a big heap of coal was piled. Two zeks were digging into it, eagerly seeking something there. When they found it, they tried it in their teeth, then put it in their sack. Then they sat themselves down and each ate a similar black-gray lump. 
>
> “What are you eating there, fellows?”
>
> And so it was that right up to nightfall the clay pit did not fulfill its work norm. Matronina gave orders that we should be left out all night. But… the electricity went out everywhere, and the work compound had no lights, so they called everyone into gatehouse. They ordered us to link arms, and with a beefed-up convoy, to the barking of the dogs and to curses, they took us to the camp compound. Everything was black. We moved along without seeing where it was we t and where the earth was firm, kneading it all up in succession, losing our footing and jerking one another.
>
> And in the camp compound it was dark. Only a hellish glow came from beneath the burners for “individual cooking”. And in the mess hall two kerosene lamps burned next to the serving window. And you could not read the slogan, not see the double portion of the nettle gruel in the bowl, and you sucked it down with your lips by feel.
>
> And tomorrow would be the same and every day; six cars of red clay---three scoops of black gruel. In the prison too, we seemed to have grown weak, but here it went much faster. There was already a ringing in the head. That pleasant weakness, in which it is easier to give in than to fight back, kept coming closer.
>
> And in the barracks---total darkness. We lay there dressed in everything wet on everything bare, and it seemed it was warmer not to take anything off---like a poultice.
>
> Open eyes looked at the black ceiling, at the black heavens.
>
> Good lord! Good Lord! Beneath the shells and the bombs I begged you to preserve my life. And now I beg you, please send me death. [194-197]



