---
title: High Brightness Workshop 2023
date: '2024-03-23'
author: Austin Hoover
categories:
  - particle accelerators
  - conferences
---


I spoke at the Workshop on High-Brightness and High-Intensity Hadron Beams (HB) at CERN a few months ago. The workshop drew around 200 attendees from the United States, United Kingdom, South Korea, China, Japan, Germany, Italy, France, and Switzerland. All slides are available [online](https://indico.cern.ch/event/1138716/timetable/#20231009.detailed). Here are some notes and highlights:


## Operations and commissioning

* The SNS has reached 1.7 MW beam power and should reach 2.8 MW this summer.

* FRIB has commissioned their accelerator and started generating [data](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.132.072501). They have a fascinating research program studying rare isotopes near the nuclear drip line.

* The European Spallation Source (ESS) has started commissioning its linac. Mamad Eshraqi talked about the practical challenges of building a brand new complex in Lund, Sweden, including environmental and radiational licenses and the impact on the community. I hadn't considered those issues before. It's interesting to see this process unfolding since I wasn't around for the SNS commissioning 20 years ago.

* China is rapidly developing several large-scale accelerator facilities. In addition to the recently commissioned China Spallation Source (CNS), they will soon introduce the Heavy Ion Accelerator Facility (HIAF), which will study nuclear physics phenomena like FRIB. HIAF will deal with all sorts of collective effects, and their GPU-accelerated end-to-end simulations are a powerful tool for modeling them. The China Initiative Accelerator Driven System (CiADS) is under construction on the same campus. CiADS will compete with [MYRRHA](https://myrrha.be/about-myrrha) to demonstrate the first accelerator-driven system, using a high-power linear accelerator to drive a subcritical nuclear reactor. I don't know if the US will ever engage in similar efforts.

* After operating for many years, the JPARC, Fermilab, ISIS, and LHC rings are being upgraded to higher energy/intensity. Most of these talks followed a similar pattern, reporting that small changes to the injection scheme, optics, etc., reduced losses.


## Beam dynamics in rings

* Adrian Oeftiger (GSI) gave a fantastic talk on the space charge limit in the FAIR synchrotron. He compared three space charge models: a *fixed frozen* model that assumes the same Gaussian distribution on each turn, an *adaptive frozen* model that scales a Gaussian to the second-order moments on each turn, and a self-consistent *particle-in-cell* model. Despite its lack of self-consistency, the fixed frozen model predicts the loss-free regions of tune space over hundreds of thousands of turns. The beams' nonuniform charge distribution washes out low-order coherent instabilities through Landau damping, rendering the particle-in-cell approach unnecessary. Adrian's simulations also showed that pulsed electron lenses---small electron beam currents that partially cancel the beam's space charge force---could increase the beam intensity by almost 100%. What is the space charge limit in a machine like the SNS, which operates with many fewer turns and a noon-gaussian charge density.

* Cristhian Gonzalez-Ortiz (MSU) has done excellent work on resonance diagram measurements and correction schemes using sextupoles in the Fermilab booster ring.

* Nick Evans (ORNL) presented our work on self-consistent injection painting (eigenpainting) to generate bright, spinning hadron beams.

* Timeofey Gorlov (ORNL) discussed the laser-assisted charge exchange (LACE) research at ORNL. We currently strip electrons from injected H- particles using thin carbon foils. LACE aims to replace the foils with lasers, enabling much higher beam power. After years of reducing the laser power requirements, LACE is ready for operational tests.

* The beam dyanmics are very complex in RHIC and the planned EIC.

* I need to study Chao's book on collective effects.


## Beam dynamics in linacs

* There was debate about 90-degree phase advance limits. Two different talks suggested that linacs could operate above this limit. For example, adding angular momentum to the beam appears to enhance stability.

* Dong-O Jeon et al. tried to clarify the relationship between "parametric instabilities" and "particle resonances." The field seems so small that people will continue to invent their own language. Perhaps we should adopt the language in Ingo Hofmann's book "Space Charge Physics for Particle Accelerators."

* Chen Xiao and Lars Groening found a way to compute matched/periodic envelopes with space charge in linear coupled focusing systems. I studied this problem for a beam with zero four-dimensional emittance, but Chen handled a more general case. It was puzzling that he did not find unique solutions while I did. I'm excited to continue studying coupled beam dynamics with space charge.

* I presented our work on the impact of high-dimensional phase space correlations on linac beam dynamics.


## Codes

* CERN has developed Xsuite, an integrated beam dynamics simulation code based on a collection of CERN codes like MAD and SixTrackLib. The code can handle almost all effects in rings. It is open-source, well-documented, and GPU-accelerated.

* LBNL has developed ImpactX in addition to their WarpX code. ImpactX is similar to PyORBIT, an s-based code used primarily for linacs. The code is well-documented and GPU-accelerated. I liked their figure illustrating the ultimate goal of simulating the entire accelerator chain. Such simulations will require modeling vastly different spatial and temporal scales by connecting the results of different simulation codes.

* I'm currently focused on PyORBIT development because it contains many SNS-specific features and will eventually connect to the SNS control room as an online model. Still, I'm excited about these open-source beam dynamics codes.


## Other things

* I enjoyed the conference, but the packed schedule left little time to explore Geneva. I would rather have fewer talks and more poster sessions.

* Some speakers covered their slides in tiny text and figures. These speakers rarely addressed anything on the slides. This is a problem at all conferences, but it was especially bad here.

* I appreciated the chance to interact with the small but highly international accelerator community.

