---
title: "*Stalin: Waiting for Hitler, 1929–1941* (Kotkin)"
author: Austin Hoover
date: 2025-12-11
categories:
    - books
    - history
---



## Part I: Equal to the Myth

> But what has been missed is that Stalin’s sociopathology was to a degree an outgrowth of the experience of dictatorial rule. [5]

> The purported science of Marxism-Leninism and the real-world construction of socialism, on the way toward Communism, offered ostensible answers to the biggest questions: why the world had so many problems (class) and how it could be made better (class warfare), with a role for all. [6]

> A human being, a Communist and revolutionary, a dictator encircled by enemies in a dictatorship encircled by enemies, a fearsome contriver of class warfare, an embodiment of the global Communist cause and the Eurasian multinational state, a ferocious champion of Russia’s revival, Stalin did what acclaimed leaders do: he articulated and drove toward a consistent goal, in his case a powerful state backed by a unified society that eradicated capitalism and built industrial socialism. [8]


### Chapter 1: Triumph of the Will

> Stalin insisted that small farms had to be consolidated to enable the mechanization and application of agronomy needed to achieve higher levels of output. [10]

> From his office (Room 521) at party headquarters on Moscow’s Old Square, he propelled the building of socialism in a furious storm of mass mobilization. His actions in 1929-30 were improvised, but they sprang from deep Marxist premises. [10]

> The savage upheaval of building socialism would also further reveal, and further shape, the darkness within Stalin’s mind. [11]

> No matter how much he crushed rivals, *he* was under siege. No matter how many enemies were deported, imprisoned, or executed, new ones emerged—and they were coming after *him*. No matter how much power he accumulated, *he* needed more. [11]

> In “How Could This Happen?” Trotsky explained his defeat by allowing that Stalin was “gifted in a practical sense, endurance, and perseverance in the pursuit of outlined goals,” but added that “his political horizon is inordinately narrow. His theoretical level is just as primitive. His pastiche booklet *Foundations of Leninism*, in which he tries to pay tribute to the party’s theoretical traditions, teems with schoolboy errors…. What is Stalin?” Trotsky concluded. “The outstanding mediocrity in our party.” [13]

> Into 1929, his seventh year as general secretary, Stalin had continued to enlarge his personal dictatorship within the Bolshevik dictatorship, and by the end of 1930 he had amassed still vaster power. 
This process of acquiring and exercising supreme power in the shadow of Lenin’s supposed Testament calling for his removal and the criticisms in the party made Stalin who he was. [67]

> Stalin had adroitly positioned himself as the incarnation of the popular will and historical necessity, but his resounding political triumph of 1929-30 had demonstrated a certain dependency, beyond even the luck of the harvest. His power rested on Mezynski and Yagoda, who were in operational command of the secret police and not personally close to him, though keen to demonstrate their loyalty—but could Stalin be sure? […] More fundamentally, Stalin’s power rested upon just four fellow politburo members: Molotov, Kaganovich, Orjonikidze, and Voroshilov. The first two seemed unlikely ever to waver. But Orjonikidze and Voroshilov? [69]


### Chapter 2: Apocalypse

> Peasants would speak of the biblical Apocalypse, some saying that the Virgin Mary had sent a letter in golden script warning that bands of horsemen would descend and destroy the collective farms. Instead, the Four Horsemen arrived in the form of the enforcement of the collectives and mass starvation. [71]

> Stalin could have seized on the intrigues to promote a favorite, such as Yevodokimov. The latter knew Stalin had no fondness for Yagoda, but he had miscalculated the dictator’s appetite for disorder in the organs, and for having Chekists force personnel decisions on him. [79]

> A land commissariat internal report in early 1932 noted that peasants were quitting the collectives by the hundreds of thousands to roam industrial sites in search of food. [93]

> Suddenly, the regime backed down from socialization of all livestock, with a decree (March 26, 1932) initiated by land commissar Yakovlev and accepted b y collectivization, but the aim was tactical: to end flight from the collectives. [94]

> Telegrams, letters, and reports swamped Sochi with news of mass death of horses, mass failure to sow crops, mass starvation, mass flight from collective farms, and a bewildering lack of government response. [101]

> Ryutin…explained that “the party has two choices: to continue meekly to endure the mockery of Leninism and the terror, and wait calmly for the final collapse of the proletarian dictatorship; or to remove this clique by force and save the cause of Communism.” [105]

> Exports cratered. In 1932, the regime would export just 1.73 million tones of grain, down from 5.06 million in 1931 and 4.76 million in 1930. Tsarist Russia in 1913 had exported more than 9 million tons of grain. [107]

> On the morning of November 9, Karolina Til found Nadya in a pool of blood in her room, near a small toy-sized pistol. […] Molotov recalled, “I had never seen Stalin weeping before, but as he stood there by the coffin, tears ran down his cheeks.” [111]

> Secret reports were now mentioning a threat of starvation even for Moscow and Leningrad. […] Absorbing his personal loss, his subjects starving, his eastern and western borders facing formidable enemies, Stalin could have been moved to carve out a breathing space. But the spring 1932 concessions had failed to produce a harvest miracle, and now he ratcheted up the repression again to squeeze blood from a stone. [112]

> Some Communists even welcomed the Nazi accession to power. Stalin did not. Still, he appears to have underestimated Hitler, as many—but not all—contemporaries did. [119]

> Upward of 50 million Soviet inhabitants, perhaps as many as 70 million, were caught in regions with little or no food. More than a million cases of typhus would be registered in 1932-33, and a half a million of typhoid fever. The OGPU claimed in a report to Stalin (March 1933) that it had interdicted 219,460 runaways in search of food, sending 186,588 back to their points of origin and arresting the others. Human and animal corpses littered county roads, railroad tracks, the open steppe, the frontiers. Peasants ate dogs and cats, exhumed horse carcasses, boiled gophers. [122]

> Reports of cannibalism in Ukraine were averaging ten per day. [122]

> Reports and letters to Stalin’s office were graphic. The documents show that he became livid not when he learned that people were driven to eating human flesh but when he learned that an American correspondent was given permission to travel to famine-stricken regions (“We already have enough spies in the USSR”). [122]

> A famine had broken out in 1891-92… Around 500,000 people died, primarily from cholera epidemics triggered by starvation. Stalin’s famine, involving extirpation of capitalism and denomadization, was incomparably worse. In 1931-33, famine and related epidemics probably killed between 5 and 7 million people. Perhaps 10 million more starved nearly to death. [127]

> Resolute in extremis, Stalin ordered the forced return of peasant escapees, the blacklisting of entire counties, and the banning of fishing in state waters or even private charity—anything that would have made it possible to avoid the collectives. [130]

> It was the famished peasants who would lift the regime and the country out of starvation, producing between 70 and 77 million tons of grain in 1933, a bumper crop comparable to the miracle of 1930. The peasants, in their land hunger and separate revolution, had made possible the advent of a Bolshevik regime in 1917-18; now enslaved, the peasants saved Stalin’s rule. [130]


### Chapter 3: Victory

> Collectivization involved the arrest, execution, internal deportation, or incarceration of 4 to 5 million peasants; the effective enslavement of another 100 million; and the loss of tens of millions of heads of livestock. [131]

> Collectivization was necessary from the point of view of Marxism-Leninism, which asserted that only a non-capitalist “mode of production” could undergird a Communist regime. [132]

> Stalin’s success in getting the creative intelligentsia in line had been uncanny. Every major cultural figure in the USSR in the 1930s had his or her own love affair with him. [186]


### Chapter 4: Terrorism

> The prospect of an assassination seemed utterly remote. [191]

> “Kirov’s been shot.” [202]

> Could Stalin have murdered his closest friend? He was capable of anything. But who, precisely, would have carried out that mission for him? [235]

> While Nikolayev reclaimed a sense of higher purpose from his despair, Stalin’s regime made the Kirov assassination into an epoch-defining event. [235]

> One of Stalin’s prime fixations was confirmed: the NKVD was asleep on the job. [236]

> Stalin was increasingly alone. Not only had both of his wives died, but now his closest friend was gone. […] The Soviet state was also to a considerable extent alone.


### Chapter 5: A Great Power

> France and Britain, to the west, and the Soviet Union, to the east, had a Hitler problem. [238]

> Hitler continued his manipulative mastery. On February 21, 1936, he granted an interview to Bertrand de Jouvenel for *Paris-Midi*, stressing his policy of peace, the unifying threat of Bolshevism, and the folly of Franco-German enmity. “Let us be friends,” the Fuhrer pleaded, calling his *Mein Kampf* outdated and promising “correction of certain pages.” [286]

> The Marxist-Leninist regime that emerged in the blood and fever dreams of the years 1929-36 was buffeted by global structural forces, from fluctuations in commodity prices to innovations in tank designs, and by the deepening of a new historical conjuncture, the mass age. [296]

> He possessed instruments Stolypin could not have dreamed of: a single-party machine that enveloped the whole country, a Soviet secret police that vastly exceeded the tsarist *okhranka* in personnel and acceptable practice, a galvanizing ideology that morally justified any and all means, and housebroken nationalisms as well as a supranational Soviet identity that bound the peoples of the former Russian empire to the regime. [297]

> By the mid-1930s the revolution and Stalin’s leadership were seen as having enabled a great country to take its rightful place among the powers, with a supposedly morally and economically superior system. [298]

> Russia’s perennial quest to build a strong state, to match an ever-superior West, had culminated, yet again, in personal rule. [299]



## Part II: Terror as Statecraft

> Socialism was no longer just libraries full of pamphlets, songs, marches, meetings, and schisms, but a country. [301]

> A few socialists began, painfully, to recognize that there could be no freedom without markets and private property, but they were denounced as apostates. [302]

> Stalin could not boast the effortless success of those to the manor born. He had to be, and was, a relentless striver. He also happened to carry a gargantuan chip on his shoulder, […] Stalin emerged as a leader of acute political intelligence and bottomless personal resentment. [303]

> The Soviet population was unprepared for what struck the country during its hour of triumph beginning in 1936. […] The peak year for Soviet executions—20,201 of them—had been 1930, during dekulakization. In the three years from 1934 to 1936, a time that included mass reprisals for the Kirov murder, the NKVD reported arresting 529,434 people, including 290,479 for counterrevolutionary crimes, and executing 4,402 of them. But for the two years 1937 and 1938, the NKVD would report 1,575,259 arrests, 87 percent of them for political offenses, and 681,692 executions. […] the total who perished directly at the hands of the Soviet secret police in 1937-38 was likely closer to 830,000. [305]

> No foreign power attacked. There was no immediate threat—social, economic, political—to the country or to the regime’s legitimacy or stability, no crisis. But then, suddenly, there was total crisis. [306]

> Special features inherent in the Soviet system made a mass and participatory terror between 1936 and 1938 possible.

> Even if Stalin remained certain of their obeisance, he was eager, like all dictators, to convert his dictatorship into despotism. For the men in his own loyal faction, in which Stalin had long taken evident pride, this meant breaking their will. Herein lay a key motivation for the fantastic terror of 1936-38. [308]

> And yet, considerations of personal power alone do not explain Stalin or the terror. [308]


### Chapter 6: On a Bluff

> The 1936 southern holiday would prove to be his most momentous yet as he further radicalized his pursuit of Trotskyites with his most frenzied public trial to date and upended international politics with a military intervention on the Iberian Peninsula. [311]

> Spain had been Europe’s only major country to avoid the Great War, and the Second Spanish Republic, born in April 1931, bucked the authoritarian trend engulfing the continent. [312]

> Spain would turn out to be important for Stalin’s mass bloodletting less as a cause than as added rationalization. [313]

> While atop his bluff overlooking the Black Sea, 850 miles from Moscow, Stalin would also decide after much hesitation to intervene in the Spanish civil war. [313]

> It was not Spain but Trotsky that riveted Stalin’s attention, including much of the attention he paid to Spain. [314]

> Stalin hated Trotsky with a deep, emotional, blind, wild hate; he also feared him, in a way he feared no one else. [322]

> Yezhov was furiously driving extraction of “testimony” for the trial of a “Trotskyite-Zinovievite Terrorist Center” in Moscow. [330]

> As for Tomsky […] he shot himself. [332]

> Well before the end of the seventy-two-hour period for appeals specified in Soviet law, Kamenev, Zinoviev, and the rest were executed in the cellars. Yezhov retrieved the bullet casings as souvenirs. [333]

> Public confessions by Lenin’s former comrades to monstrous state crimes and the rabid saturation propaganda about hidden enemies had revolutionized the political atmosphere. [336]

> Yagoda would spend the next two months on sick leave; he did not make a run for it or try to organize an “accident” to eliminate Yezhov (let alone Stalin). This was the first removal of an NKVD chief. [345]

> “The USSR constitution is the only thoroughly democratic constitution in the world.” —Stalin. [354]

> Stalin judged that a Communist takeover in China would never produce a regime strong enough to hold off the Japanese military. [359]

> Stalin, to a considerable extent, held the fate of China and, indeed, Asia in his hands. [361]

> Had Stalin been driven predominantly by vengeance, he would have ordered Chiang killed (or just let it happen). But Stalin acted from his sense of strategy. The same applied to his domestic terror. [362]

> Had Chiang been killed, Chinese accommodation with Japan, at Soviet expense, was a likely outcome. […] This could have resulted in a Japanese thrust northward, into Soviet territory, instead of southward in Asia—and therefore no Pearl Harbor or war with the United States. [367]
> Conversely, had Chiang not gone to Xi’an and been kidnapped and ultimately released, he would likely have crushed the Chinese Communists and killed or chased Mao out to Mongolia or Siberia, without forfeiting Stalin’s military aid. [367]

> “Fascism”, Stalin stated, “is poppycock. It is a temporary phenomenon.” [370] 


### Chapter 7: Enemies Hunting Enemies

> The NKVD was suffering a massacre—and not *after* it had arrested at least 1.6 million people but all the while it was doing so. [376]

> Following the executions of Kamenev, Zinoviev, Pyatakov, and others in the two public trials of August 1936 and late January 1937, massacres of NKVD state security and Red Army officers would come as a shock. [376]

> What great power has ever executed 90 percent of its top military officers? What regime, in doing so, could expect to survive? An assault on such scale, and without regime collapse, could only happen within the structures of a one-party Leninist regime and, ultimately, the conspiratorial worldview and logic of Communism, a Manichean universe of two camps and pervasive enemies. The combination of Communist ways of thinking and political practice with Stalin’s demonic mind and political skill allowed for astonishing bloodletting. [378]

> At around dusk, his wife, Zinaida, heard a gunshot in the bedroom. Orjonikidze was dead. [384]

> The far-lunch operations of Stalin’s regime were riddled with cross-purposes, self-dealing, and underfulfillment of economic targets, poor record keeping, reports of faked successes, pervasive misappropriation of state funds, and victimization of the weakest officials as scapegoats. The “system” was an unwieldy amalgam of competing clans and impossible rules, vast webs of relationships and red-tape procedures overlaid with a tableau of powerful myths (including the myth of the system itself). [390]

> Yagoda’s arrest was stunning. [393]

> Other stunning arrests followed. [393]

> Through it all, the NKVD never broke down, let alone rebelled. The ease with which Yagoda was destroyed proved that there was no threat whatsoever to Stalin’s rule. The secret police, even under assault, remained an utterly reliable instrument of his will, a testament to both the limits of the feared yet despised Yagoda’s authority and the strength of Stalin’s as supreme leader. [394]

> Stalin dictated, edited, and pored over the interrogation protocols, then circulated and referred to them as if they were factual. [415]

> Yezhov wielded nearly unimaginable power and terrified a vast country, but he never felt at ease. [416]

> “Comrades, I hope no one doubts now that a military-political plot against Soviet power existed.” —Stalin [418]

> Stalin could murder anyone on the flimsiest of pretexts, or even without a pretext, and in doing so he could assert that he was fighting tooth and nail to defend socialism and the Soviet state against the kind of rightist military putsch he has been warning about for years, and that Spain concretized. [429]

> Joseph Goebbels recorded in his diary that Hitler judged Stalin “likely diseased in the brain. Otherwise one cannot explain his bloody rule.” [432]


### Chapter 8: “What Went on in No. 1’s Brain?”

> Had Stalin aimed only to break his inner circle, utterly cow the wider elite, and make himself a despot, he might have ended the terror with the in-camera trial and executions of the military men and the arrests of Yagoda, Pauker, and the other NKVD higher-ups. Mission accomplished. But he had much larger aims, with plans for more high-profile trials. [433]

> The only way into Stalin’s serpentine mind—or, as Authur Koestler put it in *Darkness at Noon*, “what went on in No. 1’s brain?”—begins with public and private comments made by him and those he instructed. [434]

> The incarceration or physical liquidation of more than a million and a half human beings apparently posed no moral dilemmas for him. On the contrary, to pity class enemies would be to indulge sentiments over the laws of objective historical development. [435]

> Given the numbers involved, the state’s violence against its own population inevitably was chaotic. Stalin lost track of people, writing next to names in interrogation protocols, “Arrest,” when they were already in custody, a point he came to recognize. [438]

> Evasive, self-serving behavior by officialdom is endemic to every authoritarian state. What was atypical—to put it mildly—was their mass extermination by their own regime. [442]

> In November 1937, the Japanese captured Shanghai, followed, on December 13, by Nanking, the Chinese Nationalist capital, where the Imperial troops proceeded to massacre up to 300,000 civilians. [470]

> “What for?” the deputy railways commissar, Livshits, had exclaimed when taken away, according to rumors in upper party circles. This unanswered question was etched all across the Soviet space, into the walls of teeming prisons and labor camps, stamped on the souls of the children carted off to orphanages, heard echoing through the execution cellars, and repeated throughout society as people wondered if they would be next. [480]

> He [Stalin] would tell minions that penetration by foreign spies was increasing, such information would then duly appear in intelligence reports sent to him, and he would cite the reports. [488]

> There *could* have been no such terror without the Communist party and its ideology, but there *would* have been no such terror without Stalin, and his profoundly dark personality, immense strength of will, and political skill. [490]

> Stalin showed no sign that he was in the least tormented by the slaughter—he received an outpouring of furious or grief-stricken letters from wives, mothers, daughters, sons, brothers of the arrested, begging for his intercession to stop the madness, and he ignored them—but he did show awareness of the security consequences of what he was doing. [491]

> The evidence for an extremely high degree of calculation behind the terror is overwhelming. [493]


### Chapter 9: Missing Piece

> A sense of doom began to close in on the secret police. [499]

> Even a despot has to have someone at the end of the phone or telegraph line to implement directives. [500]

> Beria ran the Caucasus the way Stalin ran the entire Soviet Union. Beria would turn out to be the missing piece. [501]

> Genius and madness may be two sides of the same coin (as Aristotle wrote), but Stalin was neither. He showed himself capable of immense foresight but also blindness. He was astonishingly hardworking yet often self-defeating, uncannily shrewd yet often narrow-minded and mulish. [552]

> What transpired in 1936-38 cannot be made wholly rational any more than absolute evil can. [552]

> Few grasped the depth of his malice. [552]



## Part III: Three-Card Monte

> Hitler was a force of nature because potential counterforces allowed him to be. [555]

> Versailles’s obsolescence offered extraordinarily fertile ground for Hitler’s appetites and, in his wake, for Stalin’s opportunism. [557]

> The Fuhrer could mesmerize people. [557]

> Hitler posed a profound danger to Stalin’s personal dictatorship as the Fuhrer not only rearmed his country but raged ever more rabidly against “Judeo-Bolshevism”, transforming Germany from a partner of convenience with the USSR during the Weimar years to menace. Stalin was bafflingly slow to come to grips with the centrality of ideology in the Nazi program. [557]

> Chamberlain allowed himself to imagine that he was “fixing” the Versailles Treaty by removing the supposed cause of German aggression: too many ethnic Germans living outside German borders. [566]

> Never mind that the NKVD had fabricated their crimes, tortured them to confess, and executed them whether they confessed or not: if only these middle and lower functionaries had been able to study the *Short Course*, they would still be alive. [570]

> Stalin had been wrestling with the problem of the state under socialism throughout the terror. Now he enumerated the state’s functions: maximizing production and military defense by mobilizing the country’s resources.
> The Soviet political landscape resembled a huge forest full of charred stumps as a wildfire raged on ahead, but Stalin, who had set that fire, was still heaping oil on it long after its catastrophic consequences had become manifest. [577]

> Stalin cannot plausibly be portrayed as a clear-eyed realpolitiker abroad and unhinged mass murderer at home; he was the same calculating, distrustful mind in both cases. [579]

> Now collectivization was behind him, and the mass terror against his own elites and others mostly behind him, but Hitler was in front of him. [579]


### Chapter 10: Hammer

> He divided the world into just two camps, and for him, as for Lenin, all diplomacy amounted to two-faced intercourse with enemies. [582]

> Europe’s collective security dilemma, drawing in Japan, had deep structural foundations. [583]

> “I [Hitler] believe”, he had written, echoing Napoleon, “my life is the greatest novel in world history.” [584]

> Hitler can look like a crude and banal figure who inexplicably took over a highly industrialized, culturally advanced, politically sophisticated country, but he had proved to be an astute student of German mass sentiment. [584]

> As NKVD chief, Beria insinuated himself deeply into the regime. [588]

> Beria’s power came to exist on a completely different plane from Yezhov’s or Yagoda’s. [589]

> So that was it: Germany foaming at the mouth with anti-Communism and anti-Slav racism, and now armed to the teeth; Britain cautious and aloof in the face of another continental war; and France even more exposed than Britain, yet deferring to London, and wary of its nominal ally, the USSR. Stalin was devastating his own country with mass murders and bald-faced mendacities, but the despot faced a genuine security impasse: German aggression and buck-passing by great powers—himself included. [593]

> Germany was gearing up for further expansion. The question was: in which direction, “east or west?” [609]

> That Trotsky was still alive was almost inexplicable. [610]

> On May 3, 1939, General Karl Bodenschatz, Goring’s adjutant, warned the French military attache in Berlin that “something is up in the East." [631]

> On May 22 in Berlin, Italy and Germany formally signed their Pact of Steel, which contained an open declaration of cooperation and binding consultation, and a secret protocol of military and economic union, directed against Britain and France. [639]

> Round and round the carousel went. German-Japanese, Western-Soviet, Western-German, and German-Italian negotiations all proceeded simultaneously. [640]


### Chapter 11: Pact

> With Japan armed in the east and Hitler armed to the teeth in the west, Stalin worried not only about a two-front war against the two powers that had defeated Russia in separate major wars earlier in the century, but about how Britain, opportunistically, might join one or even both. [643]

> Hitler, with his decision to attack Poland despite British and French guarantees, had effectively backed himself into a corner, and time was running out: also on August 7, Soviet intelligence reported to Stalin that Hitler’s attack on Poland could commence as soon as August 25. Suddenly Stalin held all the cards. The despot played it slow. The tension in Berlin reached near hysteria. Chamberlain, too, had played right into Stalin’s hands, but, unlike Hitler, the British PM appeared to be taking Stalin for a fool. [657]

> It was evident that Stalin had spies high up in the German foreign ministry. [665]

> Japanese intelligence continuously, egregiously, underestimated Soviet capabilities. [668]

> Stalin had effectively organized an auction for a sphere of influence in Eastern Europe. In the event, the British made no offer. Whatever Stalin’s preferences, Hitler presented not just the better deal, but the only deal. [673]

> The PM’s worst nightmare was well-founded: that if Britain invited the Soviets to help beat back Hitler, Stalin would take advantage and Communism would end up occupying the heart of Europe. [674]

> Hitler’s decision making appears linear only in retrospect. [675]

> On September 1, after an air bombardment before dawn, 62 Wehrmacht divisions—nearly 1.5 million men—ripped into Poland, in Hitler’s biggest yet roll of what Bismarck had called the “iron dice”. [678]

> That Stalin somehow trusted Hitler was laughable, as Hitler himself noted. Stalin trusted no one. [681]

> Nazi propaganda portrayed the war as having been imposed on Germany, a necessity for the survival of the German race—a mutilation of the truth that a majority of Germans appear to have accepted, leavened, as it was, with lurid fables of Polish atrocities and German victimhood. [688]

> Soviet dishonesty and spite were epic. [690]

> Hitler was driving world politics. [698]

> Hitler remained volatile. As Warsaw was still burning, in mid-September 1939, Hitler had returned from his triumphal promenade in Danzig and ordered a gathering of his military brass to prepare for an attack against the West at the end of October—that is, within a few weeks. [700]


### Chapter 12: Smashed Pig

> To be sure, in contrast to Hitler’s impulsive high-stakes gambling, Stalin usually readied the ground before acting. With Finland, however, he would end up taking a largely unprepared gamble, and without realizing he was doing so. [705]

> If the Pact with Hitler had involved Stalin’s first high-stakes test in the modern diplomatic arts, Finland, unexpectedly, would entail his first trial by fire in the modern military arts, and the results initially proved disastrous. [705]

> Stalin emerged from the war he launched against Finland with both a crushing victory and severely impaired military reputation, emboldening the country’s potential enemies, maybe even more than he had with his executions of his own military. [760]


### Chapter 13: Greed

> Churchill, however, steadfastly refused all entreaties to seek terms with Hitler, a man he would never meet, but whose measure he took. [764]

> Stalin had gone in deeper than ever with Nazi Germany. [764]

> Beyond his greed and distraction, Stalin’s inability to pick up on the political changes in London was driven by an abiding antipathy toward the Western powers. [765]

> Hitler took Stalin’s Baltic annexations badly. [773]

> Hitler stood at a new zenith of power in July 1940. And yet, despite all his conquests and Britain’s manifest inability to dislodge him from the continent, the British government vowed to keep fighting. [782]

> Hitler’s failure to subdue Britain was eating at him. [794]

> From the start, the Soviet-German rapprochement had been fraught—burdened with tensions and uncertainties. [819]

> Soviet insiders continued to exhibit confidence bordering on arrogance. [819]

> Khrushchev, who was in Moscow when Molotov returned from Berlin, would remark, “In Stalin’s face and in his manner, one could sense agitation and, I would add, fear." [821]


### Chapter 14: Fear

> *Everyone* was talking. They had “heard” that Hitler would attack. It would happen this way. It would happen that way. It would occur on this date. It would occur on that date. [822]

> For Hitler, annihilation of the Soviet Union and international Jewry was an end in itself. But he had a further aim, forced upon him, in his view, by necessity: to establish the equivalent of a British empire or U.S. transcontinentality by conquering and racializing Eastern Europe and the Soviet Union. It was his awe and fear of U.S. power, ultimately, that propelled him to take on what he long said needed to be done: eradicate “Judeo-Bolshevism”. [834]

> Stalin saw the world in the darkest hues, as shaped by unseen sinister forces, with enemies lurking everywhere and no one’s motives to be trusted. [884]


## Coda: Little Corner, Saturday, June 21, 1941

> Stalin paced and paced in his Kremlin office, with his usual short steps, gripping a pipe in the hand of his good arm. It was Saturday, June 21, 1941. [886] 

> For a full year now, essentially since the stunning fall of France to the Germans in June 1940, he had lived in a state of unbearable tension. [887]

> “The beginning of every war is like opening the door into a dark room,” Hitler had told one of his private secretaries. “One never knows what is hidden in the darkness.” [901]

> Hitler’s racial, Social Darwinist, zero-sum understanding of geopolitics meant that both the USSR and Great Britain would have to be annihilated in order for Germany to realize its master race destiny. [904]

> Hitler, one scholar has reminded us, cannot be explained in terms of his social origins or his early life and influences, a point that is no less applicable to Stalin. [905]

> When the bust of Bismarck was transferred from the old German Chancellery to Hitler’s new Nazi Chancellery, it had broken off at the neck. […] The omen of Bismark’s broken neck was kept from the Fuhrer. [906]


