---
title: "Gerald Minerbo"
author: Austin Hoover
date: 2025-04-27
toc: false
---


I found out that Gerald Minerbo, author of MENT, passed away recently. Here's his [obituary](https://jhvonline.com/dr-gerald-minerbo-p34697-124.htm).


> Dr. Gerald Nelson Nessim Minerbo, a distinguished mathematician and physicist, passed away at his home on Tuesday, March 18, 2025, in Missouri City, Texas.
>
> Gerry, as he was called by those who loved him, was born in Alexandria, Egypt, to Salvator and Lily Minerbo (nee Farhi). His family fled Egypt in 1956 due to political uncertainty and religious persecution, landing in New York City.
> 
> Gerald earned a B.S. in applied math from Brooklyn Polytechnic School of Engineering and earned his Ph.D. in applied mathematics and theoretical physics from the University of Cambridge in 1968 under the mentorship of Richard J. Eden.
> 
> Gerald married Dr. Grace Moffat in August 1966. Together, they had two children, Julie and Geoffrey. They lived briefly in New York, Buenos Aires, Argentina and Los Alamos, New Mexico, before settling in Missouri City, Texas, in August 1981.
> 
> During his career, Gerald worked at Brookhaven National Laboratory, Los Alamos National Laboratory and Schlumberger, for over 30 years, when he retired. Of his many patents, one of his most notable was The Periscope, which was very beneficial for drilling and exploration.
> 
> He made significant advancements in the physical sciences, earning over 80 U.S. patents and publishing in countless academic journals. Most notably, his work on the Maximum Entropy (MENT) method has been influential in data analysis and modeling. Recent studies have built upon his foundational research applying N-dimensional MENT to experimental data, demonstrating the enduring impact of his work.
> 
> In addition to his theoretical contributions, Dr. Minerbo was involved in the practical applications of his research. He co-authored studies on directional electromagnetic measurements for well placement and formation evaluation while drilling, showcasing his interdisciplinary expertise in both physics and engineering. He served as an independent consultant following his retirement from Schlumberger.
> 
> Gerald was preceded in death by his wife, Dr. Grace Moffat Minerbo, who passed away in 2005, and sister, Claude Sasson, who passed away in 2022. He is survived by his daughter, Julie; and son, Geoffrey; his sister, Hedy; and several nieces and nephews who marvel at his genius and his love for his work.
> 
> Dr. Minerbo’s legacy of intellectual rigor and dedication to science will be remembered by colleagues, friends and family. Gerry was incredibly brilliant, accomplished, passionate and knowledgeable on a vast array of topics. He was very generous, passionate about learning and had a wicked sense of humor.

